In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [6]:
x
y

array([ 5, 20, 14, 32, 22, 38])

In [9]:
model = LinearRegression().fit(x, y)
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")
print(f"intercept: {model.intercept_}")


print(f"slope: {model.coef_}")

coefficient of determination: 0.7158756137479542
intercept: 5.633333333333329
slope: [0.54]


In [11]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")


print(f"slope: {new_model.coef_}")

intercept: [5.63333333]
slope: [[0.54]]


In [12]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")


predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [14]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")


predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
